name: ally check
on: [push]
jobs:
  check-a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install @axe-core/cli -g
      - run: axe www.deque.com --exit